engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
exclude_paths:
- assets/javascript/layzr.js
ratings:
  paths:
  - assets/**/*
  - bin/*
  - lib/**/*
